name: Helm Chart - Release

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**' # only execute if we have helm chart changes
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: "Get app version from package.json"
        id: get_hookshot_version
        run: |
          echo "hookshot_version=$(cat package.json | yq .version)" >> "$GITHUB_OUTPUT"

      - name: Set chart appVersion to current package.json version
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: |
            yq -i '.appVersion="${{steps.get_hookshot_version.outputs.hookshot_version}}"' helm/hookshot/Chart.yaml
    
      - name: Set values hookshot config to current config.sample.yml contents
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: |
            yq -i eval-all 'select(fileIndex==0).hookshot.config = select(fileIndex==1) | select(fileIndex==0)' helm/hookshot/values.yaml config.sample.yml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config: helm/cr.yaml
          charts_dir: helm/