name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - changelog.d/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - changelog.d/**'

  workflow_dispatch:
  merge_group:

jobs:
  lint-node:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
    - run: yarn --ignore-scripts
    - run: yarn lint:js

  lint-rust:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: rustfmt
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -Dwarnings

  config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: yarn # Need to build scripts to get rust bindings
      - run: yarn --silent ts-node src/config/Defaults.ts --config | diff config.sample.yml - 

  metrics-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: yarn # Need to build scripts to get rust bindings
      - run: yarn --silent ts-node ./scripts/build-metrics-docs.ts | diff docs/metrics.md - 
  
  test:
    # Test on LTS-1
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node_version: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - run: yarn
      - run: yarn test:cover
